# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# Fcitx5
exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace &
exec-once=fcitx5-remote -r
bind=ALT,space,execr,fcitx5-remote -t

#exec-once
exec-once=wal
exec-once = dbus-update-activation-environment WAYLAND_DISPLAY  DISPLAY

# Dolphin Fix
env = XDG_MENU_PREFIX,arch-

#Lid Shut Sleep
bind = , switch:Lid Switch, exec, systemctl suspend

#nautilus transparency
windowrulev2 = opacity 0.75 override 0.65 override, class:^(org.gnome.Nautilus)$
windowrulev2 = opacity 0.85 override 0.75 override, class:^(com.discordapp.Discord)$

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Blur for waybar
#layerrule = blur, waybar
